'use client';
import {useState,useRef} from 'react';
import {useData,useAction,Heading,Panel,Field,Status,Empty} from '@/components/ui';
import {useAuth} from '@/hooks/useAuth';
import {send,currency,localDate} from '@/lib/api';
import {unitLabel,quantityStep} from '@/components/StockQuantity';
import type {Product} from '@/types';

type Supplier={id:number;name:string;phone:string;outstanding:string};
type Purchase={id:number;reference:string;date:string;supplier__name:string;total:string;items:{product__name:string;quantity:number;total:string}[]};
type Expense={id:number;date:string;category:string;description:string;amount:string;void_reason:string};
type Count={id:number;product__name:string;expected:number;counted:number;reason:string};
type Profit={revenue_ex_tax:string;cost_of_goods:string;gross_profit:string;expenses:string;net_profit:string};
type Ledger={supplier:Supplier;ledger:{id:number;date:string;note:string;amount:string;method:string}[]};
type Tracked={lots:{id:number;batch:string;expiry:string|null;available:number}[];serials:{id:number;serial:string;status:string;warranty_until:string|null}[]};

function MoneyInput({name,defaultValue='0',required=true}:{name:string;defaultValue?:string;required?:boolean}){return <input name={name} type="number" min="0" step="0.01" defaultValue={defaultValue} required={required}/>;}
function Method(){const shop=useData<{payment_methods:string[]}>('/shop/');return <Field label="Payment method"><select name="payment_method">{(shop.data?.payment_methods||['CASH','UPI','CARD']).filter(m=>m!=='CREDIT').map(m=><option key={m}>{m}</option>)}</select></Field>;}
function DataTable({headers,rows}:{headers:string[];rows:React.ReactNode[][]}){return rows.length?<div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>:<Empty text="No records yet."/>;}

export default function Operations(){
 const {can}=useAuth();
 const tabs=[['suppliers','Suppliers','purchases.manage'],['purchases','Purchase bills','purchases.manage'],['expenses','Expenses','expenses.manage'],['profit','Profit','reports.view'],['counts','Stock counts','inventory.adjust'],['tracking','Batches & serials','inventory.adjust'],['import','Import products','prices.write'],['labels','Barcode labels','products.write']].filter(x=>can(x[2]));
 const [tab,setTab]=useState(tabs[0]?.[0]||'');
 const products=useData<Product[]>('/products/');
 return <><Heading title="Shop operations" description="Purchases, operating costs and inventory controls."/><div className="tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
 <Status loading={products.isLoading} error={products.error} retry={products.refetch}/>
 {tab==='suppliers'&&<Suppliers/>}{tab==='purchases'&&<Purchases products={products.data||[]}/>}{tab==='expenses'&&<Expenses/>}{tab==='profit'&&<ProfitReport/>}{tab==='counts'&&<Counts products={products.data||[]}/>}{tab==='tracking'&&<Tracking products={products.data||[]}/>}{tab==='import'&&<ImportProducts/>}{tab==='labels'&&<Labels products={products.data||[]}/>}
 {!tabs.length&&<Empty text="Ask the owner for access to shop operations."/>}</>;
}

function Suppliers(){
 const q=useData<Supplier[]>('/suppliers/');const action=useAction();const [selected,setSelected]=useState('');const ledger=useData<Ledger>('/suppliers/'+selected+'/',!!selected);const key=useRef(crypto.randomUUID());
 return <><Panel title="Add supplier"><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const result=await action.run(()=>send('/suppliers/',Object.fromEntries(new FormData(form))),'Supplier saved');if(result)form.reset();}}><div className="form-grid"><Field label="Supplier name"><input name="name" required maxLength={150}/></Field><Field label="Phone"><input name="phone" maxLength={20}/></Field><Field label="GSTIN"><input name="gstin" maxLength={15}/></Field><Field label="Address"><input name="address"/></Field><Field label="Opening payable"><MoneyInput name="opening_balance"/></Field></div><button className="btn primary" disabled={action.busy}>Add supplier</button></form></Panel>
 <Status loading={q.isLoading} error={q.error} retry={q.refetch}/><Panel title="Supplier balances"><DataTable headers={['Supplier','Phone','Outstanding','Ledger']} rows={(q.data||[]).map(x=>[x.name,x.phone,currency(x.outstanding),<button key={x.id} className="btn small" onClick={()=>{setSelected(String(x.id));key.current=crypto.randomUUID();}}>Open ledger</button>])}/></Panel>
 {selected&&<Panel title={ledger.data?.supplier.name||'Supplier ledger'}><Status loading={ledger.isLoading} error={ledger.error} retry={ledger.refetch}/><DataTable headers={['Date','Entry','Amount','Method']} rows={(ledger.data?.ledger||[]).map(x=>[x.date,x.note,currency(x.amount),x.method])}/><p>Outstanding: {currency(ledger.data?.supplier.outstanding||0)}</p><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));const result=await action.run(()=>send('/suppliers/'+selected+'/payments/',{...data,request_key:key.current}),'Supplier payment recorded');if(result){key.current=crypto.randomUUID();form.reset();}}}><div className="form-grid"><Field label="Payment amount"><MoneyInput name="amount"/></Field><Method/><Field label="Payment date"><input name="date" type="date" defaultValue={localDate()} max={localDate()} required/></Field><Field label="Payment note"><input name="note" required maxLength={500}/></Field></div><button className="btn primary" disabled={action.busy}>Record supplier payment</button></form></Panel>}</>;
}

type PurchaseLine={product_id:string;quantity:string;unit_cost:string;tax:string;batch:string;expiry:string;serials:string};
const newLine=():PurchaseLine=>({product_id:'',quantity:'1',unit_cost:'0',tax:'0',batch:'',expiry:'',serials:''});
function Purchases({products}:{products:Product[]}){
 const suppliers=useData<Supplier[]>('/suppliers/');const q=useData<Purchase[]>('/purchases/');const action=useAction();const key=useRef(crypto.randomUUID());const [lines,setLines]=useState<PurchaseLine[]>([newLine()]);
 const update=(i:number,field:keyof PurchaseLine,value:string)=>setLines(old=>old.map((x,n)=>n===i?{...x,[field]:value}:x));
 return <><Panel title="Receive a purchase bill"><p className="muted">Quantities use each product’s stock unit. Unit costs exclude tax; enter the supplier’s tax amount for each line. Saving adds stock and updates the supplier ledger and average purchase cost.</p><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));const result=await action.run(()=>send('/purchases/',{...data,items:lines,request_key:key.current}),'Purchase received');if(result){key.current=crypto.randomUUID();setLines([newLine()]);form.reset();}}}><div className="form-grid"><Field label="Supplier"><select name="supplier_id" required><option value="">Choose supplier</option>{suppliers.data?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Supplier bill number"><input name="reference" required maxLength={100}/></Field><Field label="Bill date"><input name="date" type="date" defaultValue={localDate()} max={localDate()} required/></Field></div>
 {lines.map((line,i)=>{const p=products.find(x=>String(x.id)===line.product_id);return <div className="notice" key={i}><div className="form-grid"><Field label={'Product '+(i+1)}><select value={line.product_id} required onChange={e=>{const product=products.find(x=>String(x.id)===e.target.value);setLines(old=>old.map((x,n)=>n===i?{...newLine(),product_id:e.target.value,unit_cost:product?.purchase_price||'0'}:x));}}><option value="">Choose product</option>{products.map(x=><option key={x.id} value={x.id}>{x.name} · {x.sku}</option>)}</select></Field><Field label={'Quantity ('+unitLabel(p?.unit||'PCS')+')'}><input type="number" step={quantityStep(p?.unit||'PCS')} min={quantityStep(p?.unit||'PCS')} required value={line.quantity} onChange={e=>update(i,'quantity',e.target.value)}/></Field><Field label="Unit cost before tax"><input type="number" min={0} step=".01" required value={line.unit_cost} onChange={e=>update(i,'unit_cost',e.target.value)}/></Field><Field label="Line tax amount"><input type="number" min={0} step=".01" required value={line.tax} onChange={e=>update(i,'tax',e.target.value)}/></Field>{p?.tracking==='BATCH'&&<><Field label="Batch number"><input value={line.batch} required onChange={e=>update(i,'batch',e.target.value)}/></Field><Field label="Expiry date"><input type="date" value={line.expiry} onChange={e=>update(i,'expiry',e.target.value)}/></Field></>}{p?.tracking==='SERIAL'&&<Field label="Serial numbers, one per line"><textarea value={line.serials} required onChange={e=>update(i,'serials',e.target.value)}/></Field>}</div>{lines.length>1&&<button className="btn small" type="button" onClick={()=>setLines(old=>old.filter((_,n)=>n!==i))}>Remove line</button>}</div>;})}
 <button type="button" className="btn" onClick={()=>setLines(x=>[...x,newLine()])}>Add purchase line</button><p>Bill total: {currency(lines.reduce((n,x)=>n+Math.round(Number(x.quantity)*Number(x.unit_cost)*100)/100+Number(x.tax),0))}</p><div className="form-grid"><Field label="Amount paid now"><MoneyInput name="paid_amount"/></Field><Method/></div><button className="btn primary" disabled={action.busy}>Receive purchase</button></form></Panel><Status loading={q.isLoading} error={q.error} retry={q.refetch}/><Panel title="Purchase history"><DataTable headers={['Bill','Supplier','Date','Total','Items']} rows={(q.data||[]).map(x=>[x.reference,x.supplier__name,x.date,currency(x.total),x.items.map(i=>`${i.product__name}: ${i.quantity}`).join(', ')])}/></Panel></>;
}

function Expenses(){
 const q=useData<Expense[]>('/expenses/');const action=useAction();const key=useRef(crypto.randomUUID());const [voidId,setVoidId]=useState<number|null>(null);
 return <><Panel title="Record expense"><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));const result=await action.run(()=>send('/expenses/',{...data,request_key:key.current}),'Expense recorded');if(result){key.current=crypto.randomUUID();form.reset();}}}><div className="form-grid"><Field label="Category"><input name="category" placeholder="Rent, salary, electricity…" required maxLength={100}/></Field><Field label="Description"><input name="description" required maxLength={500}/></Field><Field label="Amount"><MoneyInput name="amount"/></Field><Field label="Date"><input type="date" name="date" defaultValue={localDate()} max={localDate()} required/></Field><Method/></div><button className="btn primary" disabled={action.busy}>Record expense</button></form></Panel><Status loading={q.isLoading} error={q.error} retry={q.refetch}/><Panel title="Expense history"><DataTable headers={['Date','Category','Description','Amount','Status']} rows={(q.data||[]).map(x=>[x.date,x.category,x.description,currency(x.amount),x.void_reason?'Void: '+x.void_reason:<button className="btn small" key={x.id} onClick={()=>setVoidId(x.id)}>Void incorrect entry</button>])}/>{voidId&&<form onSubmit={async e=>{e.preventDefault();const reason=new FormData(e.currentTarget).get('reason');if(await action.run(()=>send('/expenses/'+voidId+'/void/',{reason}),'Expense voided'))setVoidId(null);}}><Field label="Void reason"><input name="reason" required maxLength={500}/></Field><button className="btn danger" disabled={action.busy}>Confirm expense void</button><button className="btn" type="button" onClick={()=>setVoidId(null)}>Cancel</button></form>}</Panel></>;
}

function ProfitReport(){const [from,setFrom]=useState(localDate());const [to,setTo]=useState(localDate());const q=useData<Profit>('/profit/?from='+from+'&to='+to);return <Panel title="Profit report"><div className="form-grid"><Field label="From"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="To"><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></Field></div><Status loading={q.isLoading} error={q.error} retry={q.refetch}/>{q.data&&<DataTable headers={['Measure','Amount']} rows={Object.entries(q.data).map(([k,v])=>[k.replaceAll('_',' '),currency(v)])}/><p className="muted">Revenue excludes sales GST. Cost uses purchase costs saved when billed. Returns are recognised on their return date. Purchase tax is excluded from stock cost; expenses are deducted as entered. This operating profit estimate excludes tax filing and depreciation.</p></Panel>;}

function Counts({products}:{products:Product[]}){
 const [id,setId]=useState('');const p=products.find(x=>String(x.id)===id);const q=useData<Count[]>('/stock-counts/');const action=useAction();const key=useRef(crypto.randomUUID());const [expected,setExpected]=useState(0);
 return <><Panel title="Physical stock count"><p className="muted">Count the actual quantity. If another sale changes stock before saving, refresh and recount. Use Batches & serials for tracked products.</p><form onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));if(await action.run(()=>send('/stock-counts/',{...data,product_id:id,expected,request_key:key.current}),'Count reconciled')){key.current=crypto.randomUUID();setId('');}}}><Field label="Count product"><select required value={id} onChange={e=>{setId(e.target.value);setExpected(products.find(x=>String(x.id)===e.target.value)?.stock_quantity||0);key.current=crypto.randomUUID();}}><option value="">Choose product</option>{products.filter(p=>p.tracking==='NONE').map(x=><option key={x.id} value={x.id}>{x.name} · {x.sku}</option>)}</select></Field>{p&&<><p>Expected: {expected} {unitLabel(p.unit)}</p><Field label="Physically counted"><input name="counted" type="number" min={0} step={quantityStep(p.unit)} required/></Field><Field label="Count reason"><input name="reason" required maxLength={450}/></Field><button className="btn primary" disabled={action.busy}>Save count and adjust stock</button></>}</form></Panel><Panel title="Count history"><DataTable headers={['Product','Expected','Counted','Difference','Reason']} rows={(q.data||[]).map(x=>[x.product__name,x.expected,x.counted,Number(x.counted)-Number(x.expected),x.reason])}/></Panel></>;
}

function Tracking({products}:{products:Product[]}){
 const [id,setId]=useState('');const p=products.find(x=>String(x.id)===id);const q=useData<Tracked>('/products/'+id+'/tracking/',!!id);const action=useAction();const key=useRef(crypto.randomUUID());
 return <Panel title="Batches, expiry, serials & wastage"><Field label="Tracked product"><select value={id} onChange={e=>{setId(e.target.value);key.current=crypto.randomUUID();}}><option value="">Choose product</option>{products.filter(x=>x.tracking!=='NONE').map(x=><option key={x.id} value={x.id}>{x.name} · {x.sku}</option>)}</select></Field><p className="muted">Enable Batch or Serial tracking when creating a product. Each size/colour variant has its own SKU and stock. Expired batches are excluded from sales; the earliest expiry is used first.</p>{p&&<><Status loading={q.isLoading} error={q.error} retry={q.refetch}/>{p.tracking==='BATCH'?<DataTable headers={['Batch','Expiry','Available','Status']} rows={(q.data?.lots||[]).map(x=>[x.batch,x.expiry||'No expiry',x.available,x.expiry&&x.expiry<localDate()?'Expired':x.expiry&&x.expiry<=localDate(new Date(Date.now()+30*86400000))?'Expires within 30 days':'Available'])}/>:<DataTable headers={['Serial','Status','Warranty until']} rows={(q.data?.serials||[]).map(x=>[x.serial,x.status,x.warranty_until||'—'])}/>}
 <form key={id} onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));if(await action.run(()=>send('/products/'+id+'/tracking/',{...data,request_key:key.current}),'Tracked stock updated')){key.current=crypto.randomUUID();form.reset();}}}><div className="form-grid"><Field label="Action"><select name="action"><option value="RECEIVE">Receive stock</option><option value="WASTE">Record wastage / retire stock</option></select></Field><Field label={'Quantity ('+unitLabel(p.unit)+')'}><input type="number" name="quantity" min={quantityStep(p.unit)} step={quantityStep(p.unit)} required/></Field>{p.tracking==='BATCH'?<><Field label="Batch number"><input name="batch" required maxLength={100}/></Field><Field label="Expiry date (for receipts)"><input name="expiry" type="date"/></Field></>:<Field label="Serial numbers, one per line"><textarea name="serials" required/></Field>}<Field label="Reason"><input name="reason" required maxLength={400}/></Field></div><button className="btn primary" disabled={action.busy}>Record tracked movement</button></form></>}</Panel>;
}

function ImportProducts(){
 const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState<{count:number;preview:{name:string;sku:string;opening_stock:number}[]}|null>(null);const action=useAction();const key=useRef(crypto.randomUUID());
 const submit=async(commit:boolean)=>{if(!file)return;const data=new FormData();data.set('file',file);data.set('commit',String(commit));data.set('request_key',key.current);const result=await action.run(()=>send<{count:number;preview:{name:string;sku:string;opening_stock:number}[]}>('/products/import/',data),commit?'Products imported':'Import validated');if(result){if(commit){setPreview(null);setFile(null);key.current=crypto.randomUUID();}else setPreview(result);}};
 return <Panel title="Import CSV or Excel products"><p>Import up to 500 new products at once. Existing SKUs are rejected. Use UTF-8 CSV or XLSX; keep SKUs and barcodes as text to preserve leading zeros. Prices exclude tax on imported products. Remove the example row from the template.</p><a className="btn" href="/api/products/import-template/">Download CSV template</a><Field label="Product file"><input type="file" accept=".csv,.xlsx" onChange={e=>{setFile(e.target.files?.[0]||null);setPreview(null);key.current=crypto.randomUUID();}}/></Field><button className="btn" disabled={!file||action.busy} onClick={()=>submit(false)}>Validate and preview</button>{preview&&<><p>{preview.count} products ready. Saving imports the complete file.</p><DataTable headers={['Product','SKU','Opening stock']} rows={preview.preview.map(x=>[x.name,x.sku,x.opening_stock])}/><button className="btn primary" disabled={action.busy} onClick={()=>submit(true)}>Import validated products</button></>}</Panel>;
}

function Labels({products}:{products:Product[]}){const [ids,setIds]=useState<number[]>([]);const [copies,setCopies]=useState(1);return <Panel title="Printable barcode labels"><p>Labels use each product’s barcode, or its SKU when no barcode is set. Up to 200 labels per PDF.</p><Field label="Copies per product"><input type="number" min={1} max={20} value={copies} onChange={e=>setCopies(Number(e.target.value))}/></Field>{products.map(p=><label className="check" key={p.id}><input type="checkbox" checked={ids.includes(p.id)} onChange={e=>setIds(old=>e.target.checked?[...old,p.id]:old.filter(x=>x!==p.id))}/>{p.name} · {p.sku}</label>)}{!!ids.length&&<a className="btn primary" target="_blank" rel="noreferrer" href={'/api/products/labels/?ids='+ids.join(',')+'&copies='+copies}>Open label PDF</a>}</Panel>;}
