'use client';
import {useState} from 'react';
import {Plus} from 'lucide-react';
import {useData,useAction,Heading,Panel,Field,Modal,Status,Badge,Empty} from '@/components/ui';
import {useAuth} from '@/hooks/useAuth';
import {send,dateTime} from '@/lib/api';
import type {StaffData,Activity,User} from '@/types';
export default function Staff(){
 const {can}=useAuth();const q=useData<StaffData>('/staff/',can('staff.manage'));const history=useData<Activity[]>('/activity/',can('staff.manage'));
 const [creating,setCreating]=useState(false);const [editing,setEditing]=useState<(User&{active:boolean})|null>(null);const [permissions,setPermissions]=useState<string[]>([]);const [role,setRole]=useState('CASHIER');const action=useAction();
 return <><Heading title="Staff & permissions" description="Give each team member the access they need."><button className="btn primary" onClick={()=>setCreating(true)}><Plus size={17}/>Add staff</button></Heading><Status loading={q.isLoading} error={q.error} retry={q.refetch}/>{q.data&&<Panel title="Team members"><div className="table-wrap"><table><thead><tr><th>Name</th><th>Username</th><th>Role</th><th>Status</th><th/></tr></thead><tbody>{q.data.staff.map(s=><tr key={s.id}><td>{s.name||s.username}</td><td>{s.username}</td><td>{s.role}</td><td><Badge tone={s.active?'green':'gray'}>{s.active?'Active':'Disabled'}</Badge></td><td>{s.role!=='OWNER'&&<div className="actions"><button className="btn small" onClick={()=>{setEditing(s);setRole(s.role);setPermissions(s.permissions);}}>Permissions / edit</button><button className="btn small danger" disabled={action.busy} onClick={()=>{if(confirm((s.active?'Disable':'Enable')+' access for '+s.username+'?'))action.run(()=>send('/staff/'+s.id+'/',{active:!s.active},'PATCH'),'Staff access updated');}}>{s.active?'Disable':'Enable'}</button></div>}</td></tr>)}</tbody></table></div></Panel>}
 <Status loading={history.isLoading} error={history.error} retry={history.refetch}/>{history.data&&<Panel title="Staff activity history"><div className="table-wrap"><table><thead><tr><th>Date & time</th><th>Staff</th><th>Action</th><th>Details</th></tr></thead><tbody>{history.data.map(a=><tr key={a.id}><td className="nowrap">{dateTime(a.created_at)}</td><td>{a.actor_name}</td><td>{a.action.replaceAll('_',' ')}</td><td>{a.detail}</td></tr>)}</tbody></table></div>{!history.data.length&&<Empty/>}</Panel>}
 {creating&&<Modal title="Add staff member" onClose={()=>setCreating(false)}><form onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const result=await action.run(()=>send('/staff/',data),'Staff account created');if(result)setCreating(false);}}><Field label="Name"><input name="name" required maxLength={150}/></Field><Field label="Username"><input name="username" required maxLength={150} autoComplete="off"/></Field><Field label="Password" hint="Share this initial password securely with the staff member."><input name="password" type="password" required minLength={8} autoComplete="new-password"/></Field><Field label="Role"><select name="role"><option value="CASHIER">Cashier</option><option value="MANAGER">Manager</option></select></Field><button className="btn primary wide" disabled={action.busy}>Create staff login</button></form></Modal>}
 {editing&&q.data&&<Modal title={'Permissions · '+editing.username} onClose={()=>setEditing(null)}><form onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const result=await action.run(()=>send('/staff/'+editing.id+'/',{...data,role,permissions},'PATCH'),'Permissions updated');if(result)setEditing(null);}}><Field label="Role" hint="Changing role loads its default permissions."><select value={role} onChange={e=>{setRole(e.target.value);setPermissions(q.data!.defaults[e.target.value]);}}><option value="CASHIER">Cashier</option><option value="MANAGER">Manager</option></select></Field><div className="form-grid">{q.data.available_permissions.map(p=><label className="check" key={p}><input type="checkbox" checked={permissions.includes(p)} onChange={e=>setPermissions(prev=>e.target.checked?[...prev,p]:prev.filter(x=>x!==p))}/>{p.replace('.',' · ').replaceAll('_',' ')}</label>)}</div><Field label="Reset password (optional)"><input name="password" type="password" minLength={8} autoComplete="new-password"/></Field><p className="notice">Staff and shop settings remain owner-only. Disabled staff cannot sign in; financial history is retained.</p><button className="btn primary wide" disabled={action.busy}>Save permissions</button></form></Modal>}</>;
}
