'use client';
import {useState,useRef} from 'react';
import Link from 'next/link';
import {useData,useAction,Panel,Field,Status} from '@/components/ui';
import {send,currency,dateTime} from '@/lib/api';
import {quantityStep} from '@/components/StockQuantity';
import type {Invoice,Shop} from '@/types';
type Return={id:number;number:string;total:string;refund:string;reason:string;created_at:string};
export default function InvoiceReturns({invoice}:{invoice:Invoice}){
 const q=useData<Return[]>('/invoices/'+invoice.id+'/returns/');const shop=useData<Shop>('/shop/');const action=useAction();const key=useRef(crypto.randomUUID());
 const [quantities,setQuantities]=useState<Record<number,string>>({});const [restock,setRestock]=useState<Record<number,boolean>>({});const [serials,setSerials]=useState<Record<number,string>>({});
 return <Panel title="Returns & exchanges"><p className="muted">Select only the returned quantities. Credit clears this invoice’s Udhar first; any excess becomes a refund record. Return money separately. For an exchange, record the return here, then create a new invoice for the replacement goods.</p><Status loading={q.isLoading} error={q.error} retry={q.refetch}/>{q.data?.map(r=><div className="notice" key={r.id}><a className="table-link" href={'/api/returns/'+r.id+'/pdf/'} target="_blank" rel="noreferrer">{r.number}</a> · {dateTime(r.created_at)} · credit {currency(r.total)} · refund {currency(r.refund)}<p>{r.reason}</p></div>)}
 {invoice.status==='ACTIVE'&&<form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));const items=invoice.items.filter(i=>Number(quantities[i.id])>0).map(i=>({item_id:i.id,quantity:quantities[i.id],restock:restock[i.id]!==false,serials:serials[i.id]}));const result=await action.run(()=>send('/invoices/'+invoice.id+'/returns/',{...data,items,request_key:key.current}),'Return recorded');if(result){key.current=crypto.randomUUID();setQuantities({});setSerials({});setRestock({});form.reset();}}}>
 {invoice.items.map(i=>{const available=i.quantity-Number(i.returned_quantity);return available>0&&<div key={i.id} className="notice"><strong>{i.name} · {available} {i.unit} returnable</strong><div className="form-grid"><Field label={'Return quantity for '+i.name}><input type="number" min={0} max={available} step={quantityStep(i.unit)} value={quantities[i.id]||''} onChange={e=>setQuantities({...quantities,[i.id]:e.target.value})}/></Field><label className="check"><input type="checkbox" checked={restock[i.id]!==false} onChange={e=>setRestock({...restock,[i.id]:e.target.checked})}/>Return to sellable stock</label>{i.serial_numbers.length>0&&<Field label={'Returned serials for '+i.name} hint={'Originally sold: '+i.serial_numbers.join(', ')}><textarea value={serials[i.id]||''} onChange={e=>setSerials({...serials,[i.id]:e.target.value})}/></Field>}</div></div>;})}
 <Field label="Return reason"><textarea name="reason" required maxLength={500}/></Field><Field label="Refund method"><select name="refund_method">{shop.data?.payment_methods.filter(m=>m!=='CREDIT').map(m=><option key={m}>{m}</option>)}</select></Field><button className="btn danger" disabled={action.busy||!Object.values(quantities).some(v=>Number(v)>0)}>Record return and refund</button> <Link className="btn" href="/billing">Bill replacement goods</Link></form>}</Panel>;
}
