'use client';
import {use,useState,useRef} from 'react';
import Link from 'next/link';
import {Download,Printer,Share2,Plus} from 'lucide-react';
import {useData,useAction,Heading,Panel,Status,Field,Modal,Empty} from '@/components/ui';
import {useAuth} from '@/hooks/useAuth';
import {currency,dateTime,send,download} from '@/lib/api';
import type {CustomerDetail,Shop,Payment} from '@/types';
import InvoiceTable from '@/components/InvoiceTable';
import WhatsAppReminders from '@/components/WhatsAppReminders';
import toast from 'react-hot-toast';
export default function CustomerProfile({params}:{params:Promise<{id:string}>}){
 const {id}=use(params);const q=useData<CustomerDetail>('/customers/'+id+'/');const shop=useData<Shop>('/shop/');const {can}=useAuth();const [tab,setTab]=useState('ledger');const [modal,setModal]=useState('');const key=useRef(crypto.randomUUID());const action=useAction();const data=q.data;const c=data?.customer;
 const open=(kind:string)=>{key.current=crypto.randomUUID();setModal(kind);};
 const save=async()=>{try{await download('/customers/'+id+'/statement/','customer-'+id+'-statement.pdf');}catch(e){toast.error(e instanceof Error?e.message:'Download failed');}};
 const reminder='Hello '+(c?.name||'')+', your outstanding balance at '+(shop.data?.name||'our shop')+' is '+currency(c?.outstanding)+'. Please arrange payment. Thank you.';
 let phone=(c?.phone||'').replace(/\D/g,'');if(phone.length===10)phone='91'+phone;
 return <><Heading title={c?.name||'Customer ledger'} description={c?c.phone+(c.gstin?' · GSTIN '+c.gstin:''):'Customer account and transaction history.'}><Link className="btn" href="/ledger">All ledgers</Link>{c&&<><button className="btn" onClick={save}><Download size={16}/>Statement</button><a className="btn" target="_blank" rel="noreferrer" href={'/api/customers/'+id+'/statement/'}><Printer size={16}/>Print</a>{can('ledger.payment')&&Number(c.outstanding)>0&&<button className="btn primary" onClick={()=>open('payment')}><Plus size={16}/>Receive payment</button>}</>}</Heading>
 <Status loading={q.isLoading} error={q.error} retry={q.refetch}/>{data&&c&&<>
 <div className="metrics"><div className="metric"><div><label>Outstanding balance</label><strong>{currency(c.outstanding)}</strong><small>{c.overdue?'Payment overdue':'Current ledger balance'}</small></div></div><div className="metric"><div><label>Total purchases</label><strong>{currency(c.total_purchases)}</strong><small>Active invoices</small></div></div><div className="metric"><div><label>Contact</label><strong style={{fontSize:16}}>{c.phone}</strong><small>{c.email||c.address||'No additional contact details'}</small></div></div></div>
 <div className="toolbar">{Number(c.outstanding)>0&&<button className="btn" onClick={()=>open('reminder')}><Share2 size={16}/>Prepare reminder</button>}{can('ledger.adjust')&&<button className="btn" onClick={()=>open('adjustment')}>Debit / credit adjustment</button>}</div>
 <div className="tabs">{['ledger','purchases','payments'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t==='ledger'?'Customer ledger':t==='purchases'?'Purchase history':'Payment history'}</button>)}</div>
 {tab==='ledger'&&<Panel title="Complete transaction history"><p className="muted" style={{marginBottom:16}}>Debit increases the amount owed. Credit reduces it. Entries are retained permanently.</p><div className="table-wrap"><table><thead><tr><th>Date & time</th><th>Transaction</th><th className="number">Debit</th><th className="number">Credit</th><th className="number">Balance</th><th>Recorded by</th></tr></thead><tbody>{data.ledger.map(l=><tr key={l.id}><td className="nowrap">{dateTime(l.transaction_date)}</td><td><strong>{l.invoice_number||l.type}</strong><small>{l.description}</small><small>{l.payment_method}</small></td><td className="number">{Number(l.amount)>0?currency(l.amount):'—'}</td><td className="number positive">{Number(l.amount)<0?currency(-Number(l.amount)):'—'}</td><td className="number"><strong>{currency(l.balance)}</strong></td><td>{l.created_by_name}</td></tr>)}</tbody></table></div>{!data.ledger.length&&<Empty text="This ledger has no transactions yet."/>}</Panel>}
 {tab==='purchases'&&<Panel title="Purchase history"><InvoiceTable invoices={data.invoices}/></Panel>}
 {tab==='payments'&&<Panel title="Payment history"><div className="table-wrap"><table><thead><tr><th>Date & time</th><th>Method</th><th>Type</th><th className="number">Amount</th><th>Note</th><th>Staff</th></tr></thead><tbody>{data.payments.map(p=><tr key={p.id}><td className="nowrap">{dateTime(p.transaction_date)}</td><td>{p.method}</td><td>{p.direction}</td><td className="number">{currency(p.amount)}</td><td>{p.note}</td><td>{p.created_by_name}</td></tr>)}</tbody></table></div>{!data.payments.length&&<Empty/>}</Panel>}
 {can('reminders.send')&&<WhatsAppReminders customerId={id} name={c.name} amount={c.outstanding} consent={c.whatsapp_consent}/>}
 {modal==='payment'&&<Modal title="Receive payment" onClose={()=>setModal('')}><p className="notice">Outstanding {currency(c.outstanding)}. Payments settle opening/general balances first, then the oldest unpaid invoices.</p><form onSubmit={async e=>{e.preventDefault();const form=Object.fromEntries(new FormData(e.currentTarget));const res=await action.run(()=>send<Payment>('/customers/'+id+'/payments/',{...form,transaction_date:form.transaction_date?new Date(String(form.transaction_date)).toISOString():undefined,request_key:key.current}),'Payment recorded and balance updated');if(res)setModal('');}}><Field label="Amount received (₹)"><input name="amount" type="number" min=".01" max={c.outstanding} step=".01" defaultValue={c.outstanding} required autoFocus/></Field><Field label="Payment method"><select name="payment_method">{(shop.data?.payment_methods||['CASH','UPI','CARD']).filter(m=>m!=='CREDIT').map(m=><option key={m}>{m}</option>)}</select></Field><Field label="Payment date and time" hint="Leave blank to use the current time."><input type="datetime-local" name="transaction_date"/></Field><Field label="Payment note"><textarea name="note" maxLength={500} placeholder="Reference number or payment details"/></Field><button className="btn primary wide" disabled={action.busy}>Record payment</button></form></Modal>}
 {modal==='adjustment'&&<Modal title="Ledger adjustment" onClose={()=>setModal('')}><p className="notice">Positive values add a debit. Negative values reduce opening/general balances. Reverse an invoice using its Void action.</p><form onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const res=await action.run(()=>send('/customers/'+id+'/adjustments/',{...data,request_key:key.current}),'Adjustment recorded');if(res)setModal('');}}><Field label="Signed amount (₹)"><input name="amount" type="number" step=".01" required/></Field><Field label="Reason"><textarea name="note" minLength={3} maxLength={500} required/></Field><button className="btn primary wide" disabled={action.busy}>Record adjustment</button></form></Modal>}
 {modal==='reminder'&&<Modal title="Payment reminder" onClose={()=>setModal('')}><p className="notice">{reminder}</p><p className="muted" style={{marginBottom:18}}>Review the message before sending. WhatsApp opens a draft; nothing is sent automatically.</p><div className="actions"><a className="btn primary" target="_blank" rel="noreferrer" href={'https://wa.me/'+phone+'?text='+encodeURIComponent(reminder)}>Open WhatsApp draft</a><button className="btn" onClick={async()=>{try{await navigator.clipboard.writeText(reminder);toast.success('Reminder copied');}catch{toast.error('Clipboard unavailable. Select and copy the message above.');}}}>Copy message</button></div></Modal>}</>}</>;
}
