# Generated by Django 5.2.17 on 2026-09-30 07:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoice',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoice',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoice',
            name='utgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='price_includes_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='taxable_value',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(default='PCS', max_length=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='utgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='price_includes_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='PCS', max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='gst_mode',
            field=models.CharField(choices=[('BASIC', 'Basic tax'), ('DOMESTIC', 'Domestic GST')], default='BASIC', max_length=12),
        ),
        migrations.AddField(
            model_name='shop',
            name='next_credit_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shop',
            name='state_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True)),
                ('reason', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note', to='shop.invoice')),
            ],
        ),
    ]
