# Generated by Django 5.2.17 on 2026-09-30 07:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customer_state_code_invoice_cgst_invoice_igst_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='whatsapp_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_consent_note',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('provider_id', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('status', models.CharField(default='CREATING', max_length=20)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_links', to='shop.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='GatewayReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_payment_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(default='REVIEW', max_length=20)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.payment')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.paymentlink')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('phone', models.CharField(max_length=20)),
                ('template', models.CharField(max_length=100)),
                ('status', models.CharField(default='QUEUED', max_length=20)),
                ('provider_id', models.CharField(blank=True, max_length=200)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='shop.customer')),
            ],
        ),
    ]
