# Generated by Django 5.2.17 on 2026-09-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customer_whatsapp_consent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedCache',
            fields=[
                ('cache_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('expires', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'shop_cache',
            },
        ),
    ]
