# Generated by Django 5.2.17 on 2026-09-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_sharedcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pieces_per_box',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='balance_after',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0), ('low_stock_threshold__gte', 0)), name='product_nonnegative_stock'),
        ),
    ]
