# Generated by Django 5.2.17 on 2026-09-30 12:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_pieces_per_box_alter_invoiceitem_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='serial_numbers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='tracking',
            field=models.CharField(choices=[('NONE', 'None'), ('BATCH', 'Batch / expiry'), ('SERIAL', 'Serial number')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('method', models.CharField(max_length=10)),
                ('void_reason', models.CharField(blank=True, max_length=500)),
                ('request_key', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField(unique=True)),
                ('digest', models.CharField(max_length=64)),
                ('count', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('request_key', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='shop.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='shop.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True)),
                ('reason', models.CharField(max_length=500)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('refund', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_parts', models.JSONField(default=dict)),
                ('request_key', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='shop.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_numbers', models.JSONField(default=list)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_parts', models.JSONField(default=dict)),
                ('restock', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='shop.invoiceitem')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='shop.salereturn')),
            ],
        ),
        migrations.CreateModel(
            name='SerialUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='AVAILABLE', max_length=10)),
                ('warranty_until', models.DateField(null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serial_units', to='shop.invoiceitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected', models.DecimalField(decimal_places=3, max_digits=15)),
                ('counted', models.DecimalField(decimal_places=3, max_digits=15)),
                ('reason', models.CharField(max_length=500)),
                ('request_key', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=100)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('available', models.DecimalField(decimal_places=3, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='LotAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('returned', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_allocations', to='shop.invoiceitem')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.stocklot')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('note', models.CharField(max_length=500)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('request_key', models.UUIDField(null=True, unique=True)),
                ('request_hash', models.CharField(blank=True, max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.purchase')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='shop.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.UniqueConstraint(fields=('product', 'batch'), name='product_batch_unique'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('supplier', 'reference'), name='supplier_bill_reference'),
        ),
    ]
