# Generated by Django 5.2.17 on 2026-10-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_supplier_customer_credit_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='warranty_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
