'use client';
import {useState,useRef} from 'react';
import {useSearchParams} from 'next/navigation';
import {Suspense} from 'react';
import {Plus} from 'lucide-react';
import {useData,useAction,Heading,Panel,Status,Field,Modal,Badge,Empty} from '@/components/ui';
import {useAuth} from '@/hooks/useAuth';
import {send,api,currency,dateTime} from '@/lib/api';
import type {Product,Movement} from '@/types';
function ProductsContent(){
 const {can}=useAuth();const params=useSearchParams();const [search,setSearch]=useState('');const [low,setLow]=useState(params.get('low')==='true');const [edit,setEdit]=useState<Product|null|undefined>(undefined);const [adjust,setAdjust]=useState<Product|null>(null);const [tab,setTab]=useState('products');const key=useRef(crypto.randomUUID());
 const products=useData<Product[]>('/products/');const categories=useData<{id:number;name:string}[]>('/categories/');const history=useData<Movement[]>('/stock-history/',tab==='history');const action=useAction();const [categoryName,setCategoryName]=useState('');
 const rows=(products.data||[]).filter(p=>(!low||p.is_low_stock)&&(p.name+' '+p.sku+' '+p.barcode).toLowerCase().includes(search.toLowerCase()));
 return <><Heading title="Products & inventory" description="Keep your product catalog and stock movements in order.">{can('products.write')&&can('prices.write')&&<button className="btn primary" onClick={()=>setEdit(null)}><Plus size={17}/>Add product</button>}</Heading>
 <div className="tabs"><button className={tab==='products'?'active':''} onClick={()=>setTab('products')}>Products</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>Stock history</button><button className={tab==='categories'?'active':''} onClick={()=>setTab('categories')}>Categories</button></div>
 {tab==='products'&&<><div className="toolbar"><input aria-label="Search products" placeholder="Search name, SKU or barcode…" value={search} onChange={e=>setSearch(e.target.value)}/><label className="check"><input type="checkbox" checked={low} onChange={e=>setLow(e.target.checked)}/>Low stock only</label></div><Status loading={products.isLoading} error={products.error} retry={products.refetch}/>{products.data&&<Panel><div className="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th className="number">Selling price</th><th className="number">GST</th><th className="number">Stock</th><th>Actions</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><strong>{p.name}</strong><small>{p.sku}{p.barcode&&' · '+p.barcode}</small></td><td>{p.category_name||'Uncategorized'}</td><td className="number">{currency(p.price)}{can('prices.write')&&<small>Cost {currency(p.purchase_price)}</small>}</td><td className="number">{p.gst_percent}%</td><td className="number">{p.stock_quantity}<small>{p.is_low_stock?<Badge tone="amber">Low stock</Badge>:'Threshold '+p.low_stock_threshold}</small></td><td><div className="actions">{can('products.write')&&<button className="btn small" onClick={()=>setEdit(p)}>Edit</button>}{can('inventory.adjust')&&<button className="btn small" onClick={()=>{key.current=crypto.randomUUID();setAdjust(p);}}>Adjust stock</button>}{can('products.write')&&<button className="btn small danger" onClick={()=>{if(confirm('Archive '+p.name+'? Historical invoice records are retained.'))action.run(()=>api('/products/'+p.id+'/',{method:'DELETE'}),'Product archived');}}>Archive</button>}</div></td></tr>)}</tbody></table></div>{!rows.length&&<Empty text="No matching products."/>}</Panel>}</>}
 {tab==='history'&&<><Status loading={history.isLoading} error={history.error} retry={history.refetch}/>{history.data&&<Panel title="Stock-in / stock-out history"><div className="table-wrap"><table><thead><tr><th>Date</th><th>Product</th><th>Change</th><th>Balance after</th><th>Reason</th><th>Staff</th></tr></thead><tbody>{history.data.map(m=><tr key={m.id}><td className="nowrap">{dateTime(m.created_at)}</td><td>{m.product_name}</td><td className={m.quantity>0?'positive':'negative'}>{m.quantity>0?'+':''}{m.quantity}</td><td>{m.balance_after}</td><td>{m.reason}</td><td>{m.created_by_name}</td></tr>)}</tbody></table></div>{!history.data.length&&<Empty/>}</Panel>}</>}
 {tab==='categories'&&<Panel title="Product categories">{can('products.write')&&<form className="toolbar" onSubmit={async e=>{e.preventDefault();const result=await action.run(()=>send('/categories/',{name:categoryName}));if(result)setCategoryName('');}}><input aria-label="Category name" placeholder="Category name" required maxLength={100} value={categoryName} onChange={e=>setCategoryName(e.target.value)}/><button className="btn primary" disabled={action.busy}>Add category</button></form>}<div className="stack">{categories.data?.map(c=><div className="total-row" key={c.id}>{c.name}</div>)}</div></Panel>}
 {edit!==undefined&&<Modal title={edit?'Edit product':'Add product'} onClose={()=>setEdit(undefined)}><form onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const payload={...data,category:data.category||null,barcode:data.barcode||null};const result=await action.run(()=>send<Product>(edit?'/products/'+edit.id+'/':'/products/',payload,edit?'PATCH':'POST'));if(result)setEdit(undefined);}}><div className="form-grid"><Field label="Product name"><input name="name" defaultValue={edit?.name} required maxLength={160}/></Field><Field label="SKU"><input name="sku" defaultValue={edit?.sku} required maxLength={80}/></Field><Field label="Barcode"><input name="barcode" defaultValue={edit?.barcode||''} maxLength={80}/></Field><Field label="Category"><select name="category" defaultValue={edit?.category||''}><option value="">Uncategorized</option>{categories.data?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>
 {can('prices.write')&&<><Field label="Purchase price (₹)"><input name="purchase_price" type="number" min={0} step=".01" defaultValue={edit?.purchase_price||'0'} required/></Field><Field label="Selling price before tax (₹)"><input name="price" type="number" min={0} step=".01" defaultValue={edit?.price} required/></Field><Field label="GST (%)"><input name="gst_percent" type="number" min={0} max={100} step=".01" defaultValue={edit?.gst_percent||'0'} required/></Field></>}
 {!edit&&<Field label="Opening stock"><input name="opening_stock" type="number" min={0} max={1000000} step={1} defaultValue={0} required/></Field>}<Field label="Low-stock threshold"><input name="low_stock_threshold" type="number" min={0} step={1} defaultValue={edit?.low_stock_threshold??5} required/></Field></div><button className="btn primary wide" disabled={action.busy}>Save product</button></form></Modal>}
 {adjust&&<Modal title={'Adjust stock · '+adjust.name} onClose={()=>setAdjust(null)}><p className="notice">Current stock: {adjust.stock_quantity}. Enter a positive number for stock-in or a negative number for stock-out.</p><form onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const result=await action.run(()=>send('/products/'+adjust.id+'/stock/',{...data,request_key:key.current}),'Stock movement recorded');if(result)setAdjust(null);}}><Field label="Stock change"><input type="number" name="quantity" required step={1} min={-adjust.stock_quantity} max={1000000}/></Field><Field label="Reason"><textarea name="reason" required minLength={3} maxLength={500}/></Field><button className="btn primary wide" disabled={action.busy}>Record stock change</button></form></Modal>}</>;
}
export default function Products(){return <Suspense fallback={<Empty text="Loading inventory…"/>}><ProductsContent/></Suspense>;}
