'use client';
import {Suspense,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {Field} from '@/components/ui';
import {useAuth} from '@/hooks/useAuth';
import {send} from '@/lib/api';
function Recovery(){const params=useSearchParams();const auth=useAuth();const [message,setMessage]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const token=params.get('token');return <main className="auth-page"><section className="auth-story"><h1>Recover your account</h1><p>Use the email saved in My account. Staff can also ask the owner to reset their password.</p></section><section className="auth-form"><h2>{token?'Set a new password':'Forgot password'}</h2><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const data=Object.fromEntries(new FormData(e.currentTarget));if(token){await send('/reset-password/',{...data,uid:params.get('uid'),token});setMessage('Password reset. You can sign in with your new password.');}else{const r=await send<{message:string}>('/forgot-password/',data);setMessage(r.message);}}catch(e){setError(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}}}>{token?<Field label="New password"><input name="new_password" type="password" minLength={8} autoComplete="new-password" required/></Field>:<><Field label="Username"><input name="username" autoComplete="username" required/></Field><Field label="Recovery email"><input name="email" type="email" autoComplete="email" required/></Field></>}<button className="btn primary" disabled={busy||auth.loading||!!auth.error}>{token?'Reset password':'Request reset link'}</button></form>{error&&<p className="notice danger" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}<Link className="table-link" href="/login">Back to sign in</Link></section></main>;}
export default function ResetPassword(){return <Suspense><Recovery/></Suspense>;}
